spring.application.name=FestivalPulse

spring.datasource.url=jdbc:mysql://localhost:3306/festivalDB?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=sql
spring.datasource.password=sql

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true